[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Output directory where the built files are located
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Environment variables for the build process
  NEXT_TELEMETRY_DISABLED = "1"

# Enable Next.js runtime for serverless functions
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js routing
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"